### ISSUE TITLE
Error while running ScriptTargets.R

### ISSUE THREAD

**Issue by tahseen-igib** [cafernandezlo/MLMicrobiomeT1D#1]
Hi,
Thanks for a wonderful script.
However, while running the following code
(https://github.com/cafernandezlo/MLMicrobiomeT1D/blob/master/Preprocessed/ScriptTargets.R) I encountered an error:- 
**Error in names(K) <- `*vtmp*` : attempt to set an attribute on NULL**
Could u please help

**Comment by cafernandezlo** [comment]
seems like you have a problem with your datasets. This error used to be related to missing colnames or colnames with special characters. 

Consider using the function make.names in order to ensure that you have syntactically valid colnames or add colnames to your dataset in case you don't.

After this, if you still have this issue, please send a minimal dataset and runnable code in order to reproduce it.
